### ISSUE TITLE
你好！博主。你上传的文件中未找到SubtitlesEditViewContainer.java文件

### ISSUE THREAD

**Issue by CyberCoder1024** [silladus/SubtitlesView#1]
博主，你好。我是从简书过来查看你的代码。你的上传工程文件中的SubtitlesEditViewContainer并没有找到。

**Comment by silladus** [comment]
> 博主，你好。我是从简书过来查看你的代码。你的上传工程文件中的SubtitlesEditViewContainer并没有找到。

有的，你仔细看一下
